@extends('layouts.app')
@section('title','设置 · 南夜维基')
@section('content')
<section class="page-hero page-hero-settings"><p class="eyebrow" data-zh="SETTINGS · 设置" data-en="SETTINGS">SETTINGS · 设置</p><h1 data-zh="设置" data-en="Settings">设置</h1><p data-zh="语言、账号与网站信息。" data-en="Language, account and website information.">语言、账号与网站信息。</p></section>
<section class="section settings-page">
<div class="settings-group"><p class="kicker" data-zh="LANGUAGE · 语言" data-en="LANGUAGE">LANGUAGE · 语言</p><div class="settings-row"><div><strong data-zh="语言 / Language" data-en="Language">语言 / Language</strong><span id="settings-language-label">简体中文</span></div><div class="settings-actions"><button type="button" data-lang-choice="zh">简体中文</button><button type="button" data-lang-choice="en">English</button></div></div></div>
<div class="settings-group"><p class="kicker" data-zh="ACCOUNT · 账号" data-en="ACCOUNT">ACCOUNT · 账号</p><div class="settings-row"><div><strong data-zh="账号 / Account" data-en="Account">账号 / Account</strong>@auth<span data-static-zh="登录状态：{{ auth()->user()->username }} · 已登录" data-static-en="Signed in as {{ auth()->user()->username }}">登录状态：{{ auth()->user()->username }} · 已登录</span>@else<span data-zh="未登录" data-en="Not signed in">未登录</span>@endauth</div><div class="settings-actions">@auth<a href="{{ route('account') }}" data-zh="个人中心" data-en="Account">个人中心</a><form method="post" action="{{ route('logout') }}">@csrf<button type="submit" data-zh="退出登录" data-en="Sign out">退出登录</button></form>@else<a href="{{ route('login') }}" data-zh="登录" data-en="Sign in">登录</a><a href="{{ route('register') }}" data-zh="注册" data-en="Register">注册</a>@endauth</div></div></div>
<div class="settings-group"><p class="kicker" data-zh="POLICIES & RULES · 政策与规则" data-en="POLICIES & RULES">POLICIES & RULES · 政策与规则</p><a class="settings-link" href="{{ route('privacy') }}"><strong data-zh="隐私政策" data-en="Privacy Policy">隐私政策</strong><span>Privacy Policy ↗</span></a><a class="settings-link" href="{{ url('/disclaimer') }}"><strong data-zh="免责声明" data-en="Disclaimer">免责声明</strong><span>Disclaimer ↗</span></a><a class="settings-link" href="{{ route('transparency') }}"><strong data-zh="透明度" data-en="Transparency">透明度</strong><span>Transparency ↗</span></a></div>
<div class="settings-group"><p class="kicker" data-zh="ABOUT · 关于" data-en="ABOUT">ABOUT · 关于</p><div class="settings-row"><div><strong>Southnight.wiki</strong><span data-zh="官方网站：southnight.uk" data-en="Official website: southnight.uk">官方网站：southnight.uk</span></div><div><strong>Version {{ $version }}</strong><span data-static-zh="构建日期 {{ $buildDate }}" data-static-en="Build date {{ $buildDate }}">构建日期 {{ $buildDate }}</span></div></div><a class="settings-link" href="{{ route('transparency') }}"><strong data-zh="更新与说明" data-en="Updates & Information">更新与说明</strong><span>Changelog ↗</span></a></div>
<div class="settings-group"><p class="kicker" data-zh="CONTACT · 联系" data-en="CONTACT">CONTACT · 联系</p><a class="settings-link" href="mailto:xiaoqiuyi@qiulan.wiki"><strong data-zh="联系南夜维基" data-en="Contact Southnight.wiki">联系南夜维基</strong><span>xiaoqiuyi@qiulan.wiki ↗</span></a></div>
</section>
@endsection
@push('scripts')
<script>(()=>{const sync=lang=>{const label=document.querySelector('#settings-language-label');if(label)label.textContent=lang==='en'?'English':'简体中文';document.querySelectorAll('[data-lang-choice]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.langChoice===lang)))};document.querySelectorAll('[data-lang-choice]').forEach(button=>button.addEventListener('click',()=>{window.SNW?.setLanguage(button.dataset.langChoice);sync(button.dataset.langChoice)}));sync(window.SNW?.getLanguage()||'zh')})();</script>
@endpush
