document.querySelectorAll('#year').forEach(el=>el.textContent=new Date().getFullYear());
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const pages=[{href:'index.html',zh:'首页',en:'Home',icon:'⌂'},{href:'about.html',zh:'关于',en:'About',icon:'○'},{href:'research.html',zh:'研究',en:'Research',icon:'◇'},{href:'leadership.html',zh:'成员',en:'People',icon:'◎'},{href:'principles.html',zh:'理念',en:'Vision',icon:'✦'}];
const current=(location.pathname.split('/').pop()||'index.html').toLowerCase(),index=Math.max(0,pages.findIndex(p=>p.href===current));
const translations={
'首页':'Home','关于':'About','研究':'Research','成员':'People','理念':'Vision','认识南夜维基':'Discover SNW','我们的成员 ↘':'Our People ↘','向南而行，':'Journey South,','探索智能的长夜。':'Explore the Long Night of Intelligence.','南夜维基是成立于英国的公益互联网组织。我们关注 AI 智能体如何真正服务人类，也持续研究互联网技术并维护网络安全。':'Southnight Wiki is a UK-founded non-profit internet organisation. We explore how AI agents can truly serve humanity, while advancing internet technologies and cybersecurity.','01 / 关于我们':'01 / About Us','技术不只关乎未来，':'Technology is not only about the future,','也关乎每一个人的现在。':'but everyone’s present.','南夜维基（Southnight.wiki）诞生于英国，是一个以公共价值为出发点的公益互联网组织。':'Southnight Wiki (SNW) was founded in the United Kingdom as a non-profit internet organisation driven by public value.','我们相信，人工智能与网络技术应当被负责任地理解、实践和分享。技术的价值，最终应由它为人类带来的福祉来衡量。':'We believe AI and internet technologies should be understood, practised and shared responsibly. Their value should ultimately be measured by the benefit they bring to humanity.','成立地':'Founded in','英国 · United Kingdom':'United Kingdom','组织性质':'Organisation','公益互联网组织':'Non-profit Internet Organisation','总策划':'General Planner','02 / 研究与实践':'02 / Research & Practice','我们正在关注':'Our Focus','从智能体的真实应用，到更可靠的互联网基础设施。':'From real-world agents to more dependable internet infrastructure.','AI 智能体实践':'AI Agent Practice','互联网技术研究':'Internet Technology','网络安全维护':'Cybersecurity','03 / 组织历程':'03 / Our History','历任站长':'Former Directors','每一任站长，都在南夜的故事里留下了一束光。':'Every director has left a light in the story of SNW.','名誉站长':'Honorary Director','让技术走向人，也让人走向更好的未来。':'Bringing technology closer to people—and people towards a better future.','关于南夜':'About SNW','以公共价值，':'Understand technology','理解技术。':'through public value.','技术最终应当':'Technology should ultimately','回应人的需要。':'answer human needs.','成立地点':'Founded in','关注领域':'Focus','研究 · 实践 · 分享':'Research · Practice · Share','研究与实践':'Research & Practice','探索技术，':'Explore technology,','也审视技术。':'and question it.','我们从真实问题出发，关注人工智能与网络技术的实践价值、安全边界和公共意义。':'We begin with real problems, examining the practical value, safety boundaries and public meaning of AI and internet technologies.','组织成员':'Our People','同行者，构成':'Our companions shape','南夜的历史。':'the history of SNW.','南夜维基的发展由历任成员共同推动。这里记录组织的策划者、历任站长及名誉站长。':'SNW has been shaped by generations of members. Here we record its planner, former directors and honorary director.','第一任站长':'1st Director','第二任站长':'2nd Director','第三任站长':'3rd Director','第四任站长':'4th Director','第五任站长':'5th Director','第六任站长':'6th Director','未实名':'Name undisclosed','愿景与原则':'Vision & Principles','善用技术，':'Use technology wisely,','而非盲从技术。':'never follow it blindly.','我们的判断始终回到一个朴素的问题：它是否让人类生活得更好？':'Our judgement returns to one simple question: does it improve human life?','以人为本':'Human-centred','开放求知':'Open Inquiry','安全负责':'Safety & Responsibility','公益导向':'Public Benefit','技术向善，实践求真。':'Technology for good. Practice grounded in truth.','上一页':'Previous','下一页':'Next','关于我们':'About Us'};
function walk(root,lang){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const raw=n.nodeValue,trim=raw.trim();if(!trim)continue;if(!n.parentElement.dataset.zh)n.parentElement.dataset.zh=trim;if(lang==='en'&&translations[trim])n.nodeValue=raw.replace(trim,translations[trim]);else if(lang==='zh'&&n.parentElement.dataset.zh)n.nodeValue=raw.replace(trim,n.parentElement.dataset.zh)}}
const main=document.querySelector('main');if(main){const prev=pages[(index+4)%5],next=pages[(index+1)%5],pager=document.createElement('nav');pager.className='page-switcher';pager.innerHTML=`<a href="${prev.href}"><small data-role="prev">← 上一页</small><strong data-zh="${prev.zh}" data-en="${prev.en}">${prev.zh}</strong></a><a href="${next.href}"><small data-role="next">下一页 →</small><strong data-zh="${next.zh}" data-en="${next.en}">${next.zh}</strong></a>`;main.appendChild(pager)}
const mobile=document.createElement('nav');mobile.className='mobile-tabs';mobile.innerHTML=pages.map((p,i)=>`<a href="${p.href}"${i===index?' class="active" aria-current="page"':''}><span>${p.icon}</span><i data-zh="${p.zh}" data-en="${p.en}">${p.zh}</i></a>`).join('');document.body.appendChild(mobile);
const toggle=document.createElement('button');toggle.className='lang-toggle';toggle.setAttribute('aria-label','切换语言 / Switch language');document.body.appendChild(toggle);
function setLang(lang){document.documentElement.lang=lang==='en'?'en-GB':'zh-CN';walk(document.body,lang);document.querySelectorAll('[data-zh][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('[data-role="prev"]').forEach(el=>el.textContent=lang==='en'?'← Previous':'← 上一页');document.querySelectorAll('[data-role="next"]').forEach(el=>el.textContent=lang==='en'?'Next →':'下一页 →');toggle.textContent=lang==='en'?'中':'EN';localStorage.setItem('snw-lang',lang)}
toggle.onclick=()=>setLang(document.documentElement.lang.startsWith('en')?'zh':'en');setLang(localStorage.getItem('snw-lang')||'zh');
